// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function PerformSampling(arg1:string,arg2:boolean,arg3:string,arg4:number):Promise<main.SamplingResult>;
